[package]
name = 'Deployer'
version = '1.0.0'

[dependencies.CedraFramework]
git = 'https://github.com/cedra-labs/cedra-network.git'
rev = '6e846b37919bd1c8e773d4248ae221546550596f'
subdir = 'cedra-move/framework/cedra-framework'

[dev-addresses]
deployer="c745ffa4f97fa9739fae0cb173996f70bb8e4b0310fa781ccca2f7dc13f7db06"

[addresses]
deployer="_"
